### ISSUE TITLE
Enchancement: Add SoupX, DIEM and Solo

### ISSUE THREAD

**Issue by mbatiuk** [compbiomed/singleCellTK#432]
There are several extra tools that really fit well into this project.

SoupX was shown to be robust and working on non-filtered droplet matrix to estimate ambient RNA level. This is similar to DecontX but does not require any prior information about data (e.g. cluster information, etc):
doi: 10.1093/gigascience/giaa151
https://github.com/constantAmateur/SoupX 

DIEM was shown to be superior to EmptyDrops to distinguish empty drops from single nuclei droplets. It also removes cell drops with high ambient contamination:
https://doi.org/10.1038/s41598-020-67513-5
https://github.com/marcalva/diem

Solo was show to be more robust comparing to other doublet detection tools (DoubletFinder and Scrublet):
https://doi.org/10.1016/j.cels.2020.05.010
https://github.com/calico/solo

I think these tools could greatly increase possibilities of singleCellTK and promote better adoption.

**Comment by joshua-d-campbell** [comment]
HI @mbatiuk, thanks for the suggestions! It may take us some time to incorporate these as we are finishing a major update to the UI. However, we will add them to the list of tools to eventually incorporate.

**Comment by joshua-d-campbell** [comment]
We have added SoupX to the toolkit and the SCTK-QC pipeline in version [v2.5.1](https://github.com/compbiomed/singleCellTK/releases/tag/v2.5.1). Unfortunately, DIEM and Solo don't appear to be in CRAN or Bioconductor. Since we are a Bioconductor package which doesn't allow dependencies in Github and for other maintainability reasons, we are trying to avoid the packages that are GitHub only. I am going to close this issue for now but we will keep these other algorithms on our potential list to include.
