### ISSUE TITLE
Shiny app "Label Cell Type" error

### ISSUE THREAD

**Issue by fangpingmu** [compbiomed/singleCellTK#572]
I am using shiny app version 2.4.1. I cannot Select assay. "Error: argument is of length zero".

https://www.camplab.net/sctk/v2.4.1/articles/articles/cell_type_labeling.html

<img width="951" alt="Screen Shot 2022-03-13 at 7 50 46 PM" src="https://user-images.githubusercontent.com/17434395/158085428-3b1d87d0-894b-46b7-bf08-c02b6a708c74.png">

**Comment by mvfki** [comment]
Hi,

This is a bug in our UI implementation. There should be a drop-down box for selecting an assay, like many other tabs. I am sorry for the inconvenience. And thanks for finding it. 

Since the R console function should still work, you can export your dataset as an SCE object and import it back to your R console and apply the `runSingleR()` function following the instruction on our [documentation](https://www.camplab.net/sctk/v2.4.1/articles/articles/cell_type_labeling.html). 

The fix for this will be available very soon. 

Best

**Comment by joshua-d-campbell** [comment]
This has been fixed in version [v2.5.1](https://github.com/compbiomed/singleCellTK/releases/tag/v2.5.1).
