### ISSUE TITLE
v2.6.0 not on campbio namespace on dockerhub

### ISSUE THREAD

**Issue by GeertvanGeest** [compbiomed/singleCellTK#595]
Hi, 

Thanks for this nice software. 

I was trying to pull v2.6.0 from docker hub (`campbio/sctk_qc:2.6.0`), but the latest tag is 2.4.1. Should I use `rz2333/sctk_qc:2.6.0` instead? 

It also gives me a bit of a cryptic error. Anything I'm missing here? 

This is the command I'm trying to run:

```sh
docker run --rm \
-v $PWD:/SCTK_docker \
rz2333/sctk_qc:2.6.0 \
-b /SCTK_docker/ \
-P CellRangerV3 \
-s SC01 \
-o /SCTK_docker/output_sctk \
-S TRUE -F Seurat
```

This is the error:

```
Loading required package: BiocParallel
[1] "The output directory is"
[1] "/SCTK_docker/output_sctk"
The output format is [Seurat]. 
Mon May 23 10:16:59 2022 .. Running droplet QC
Mon May 23 10:16:59 2022 ... Running 'perCellQCMetrics'
Error in validObject(.Object) : invalid class “RegularArrayGrid” object: 
    grid is too coarse (all grid elements must have a length <=
    .Machine$integer.max)
Calls: runDropletQC ... RegularArrayGrid -> new -> initialize -> initialize -> validObject
Execution halted
```

This is the tree of my CellRangerv3 input:

```
./
└── SC01
    └── outs
        ├── filtered_feature_bc_matrix
        │   ├── barcodes.tsv.gz
        │   ├── features.tsv.gz
        │   └── matrix.mtx.gz
        ├── metrics_summary.csv
        └── raw_feature_bc_matrix
            ├── barcodes.tsv.gz
            ├── features.tsv.gz
            └── matrix.mtx.gz

4 directories, 7 files
```

Thanks in advance!

**Comment by rz2333** [comment]
Hi,

The campbio/sctk_qc:2.6.0 will be available soon. You can definitely try that for now. 

I will look into the bug because I had never seen this before using docker before. That bug might be due to the size of the droplet matrix (including all empty droplets so it's huge). But if you want to perform the QC while I am debugging, you can try to specify -d as Cell. This will perform standard QC on the cell matrix only (matrix without empty droplet, which is under filtered_feature_bc_matrix folder). 

Thanks,
Rui

**Comment by rz2333** [comment]
Hi Geert,

You can pull down rz2333/sctk_qc:2.6.0 and try with your command again (without the need of specifying -d argument). I update a package that might fix the error in running 'perCellQCMetrics' step. Please let me know whether the error is still there. 

Also, you can specify number of cpu by specifying argument -n. Running perCellQCMetrics for droplet count matrix takes a long time without parallelization. 

Thanks,
Rui

**Comment by rz2333** [comment]
Hi Geert,

Interesting. Might I know how many cells are in your dataset? It could be due to a memory issue of the docker (parallelization might make multiple copies of the data). 

By the way, could you try to increase the resource limit for docker? It's in the Preference setting of docker:
<img width="1045" alt="Screen Shot 2022-05-23 at 12 48 59 PM" src="https://user-images.githubusercontent.com/16445398/169869400-59965a39-9ae2-4318-a041-449e67e7baa5.png">

Could you try to increase the number of CPU and memory before you try again? Please let me know if it still doesn't work. 

Thanks,
Rui

**Comment by GeertvanGeest** [comment]
Thanks again for the response @rz2333 . It was indeed a memory issue. Apparently docker isn't very verbose regarding out-of-memory errors. So, I gave it a go with singularity on a compute cluster:

```sh
singularity run \
  --bind /data \
  ${PROJDIR}/containers/sctk_qc_2.6.0.sif \
    -b ${PROJDIR}/cellranger \
    -P CellRangerV3 \
    -s "SC01" \
    -o ${PROJDIR}/sctk_test3 \
    -S TRUE \
    -F SCE,AnnData,FlatFile,Seurat \
    --detectCells=TRUE \
    --detectMitoLevel=TRUE \
    --mitoType=human-ensembl \
    -n 4
```

Apologies for not using the exact same options as in my example above.. 

Indeed, it took quite a bit of memory (64.38 GB max; my PC would not be able to accommodate this), but I wouldn't say the dataset is particularly large (8,470 estimated cells; 65,313 reads/cell according to the cellranger report). 

However, after it started writing to the output directory, it ran into another error:

```
Tue May 24 11:46:12 2022 .. Writing '/data/projects/p682/sctk_test3/SC01/FlatFile/Droplets/SC01_cellData.txt.gz
Tue May 24 11:46:21 2022 .. Writing '/data/projects/p682/sctk_test3/SC01/FlatFile/Droplets/SC01_featureData.txt.gz
Tue May 24 11:46:21 2022 .. Writing metadata to /data/projects/p682/sctk_test3/SC01/FlatFile/Droplets//metadata/SC01_metadata.rds
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102
Calls: exportSCE ... .sce2adata -> as.matrix -> as.matrix -> as -> asMethod
In addition: Warning messages:
```

Is there a (small) dataset (i.e. cellranger output) + command that should work with the docker image? 

Thanks again for your help!

**Comment by rz2333** [comment]
Hi Geert,

Thanks for trying the docker! I would not suggest outputting the Seurat object when you run QC on both droplet and the cell matrix. The number of barcodes in the droplet matrix (raw_feature_bc_matrix) is ~ 7 million. Converting such a big dataset into a Seurat object can cause problems and it's not very helpful for downstream analysis. I would skip 'Seurat' in the -F argument in this case. 

If you would like to perform QC on the matrix that contains true cells, you can specify that using '-d' argument as Cell (https://camplab.net/sctk/v2.6.0/articles/cmd_qc.html#:~:text=%2Dd%2C%20%2D%2DdataType,processes%20cell%20data). In this case, it's safe to output the Seurat object. 

As for the memory issue, I think that's due to the 'doubletFinder' step. We are thinking about removing it from the docker since it's taking a lot of memory. It should fix the memory issue in our future release. Please let me know if you still have any problems with the docker. Happy to help!

Thanks,
Rui

**Comment by mvfki** [comment]
Hi Geert,

Our new release version v2.7.1 99e76b9c3899ca13df27dea871b9e1b183bb1636 is out and the issue previously mentioned is fixed. You can install it with the following command in the R console to test it out. The docker image will also be updated soon. 

```r
if (!requireNamespace("devtools", quietly = TRUE))
    install.packages("devtools")
devtools::install_github("compbiomed/singleCellTK")
```

Best,
Yichen

**Comment by mvfki** [comment]
@GeertvanGeest The new version of SCTK Shiny APP is uploaded to Docker Hub (https://hub.docker.com/r/campbio/sctk_shiny/). You can test by pulling it with
```bash
docker pull campbio/sctk_shiny:v2.7.1
```
