### ISSUE TITLE
importMitoGeneSet function not available

### ISSUE THREAD

**Issue by shantanubSanofi** [compbiomed/singleCellTK#605]
Hi, I have recently successfully installed the singleCellTK package. However, I'm not able to access the function "importMitoGeneSet". 

When I try to run the _importMitoGeneSet_ function it says function not available.

Please guide me on how to resolve the same.

**Comment by mvfki** [comment]
Hi @shantanubSanofi ,

That is super weird. At least it exists on my end with the latest release version. Two possible checks for now is: 
1. Have you installed a latest release version of `singleCellTK`. This can be either from our GitHub release or the Bioconductor release.
2. Have you run `library(singleCellTK)` to load the package to your R environment before you call the function?

If these seem fine, we might need your session info to see if we can find any other reasons. (run `sessionInfo()` in R and paste the result in this thread)

Best,
Yichen

**Comment by shantanubSanofi** [comment]
![image](https://user-images.githubusercontent.com/109298520/179022190-73a1e7e1-74d3-40a2-8f9b-92199adc38e3.png)

**Comment by mvfki** [comment]
Does this only happen to the function `importMitoGeneSet()`? Would you mind trying any other `singleCellTK` function?

**Comment by mvfki** [comment]
Emm this is weird and hard to figure out now. I have some random ideas maybe you can try.

1. What does it say if you use `singleCellTK::importMitoGeneSet()` instead of directly using `importMitoGeneSet()`?
2. What about starting a new R session, run `library(singleCellTK)`, call `importMitoGeneSet()`? (Don't need to run your script or import your data)
3. Version 2.6.0 should be from Bioconductor. Would you mind giving it a shot with our GitHub version, by running `devtools::install_github("compbiomed/singleCellTK")`
