### ISSUE TITLE
Error in SoupX & emptyDrops

### ISSUE THREAD

**Issue by XanderChen0530** [compbiomed/singleCellTK#608]
Hi scTK team,
Thank you for developing this useful tool.  I found some errors when I analyzed this dataset GSE128423, https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE128423.  These errors happened just for b1(GSM3674239) and std*(GSM3674224 to GSM3674229) samples.

Here is my code:
`docker run  --rm -v ~/sc_Projects/Data/Cell_BM_Taxonomy:/SCTK_docker \
  -it campbio/sctk_qc:2.6.0 \
  -R SCTK_docker/b1 \
  -P CellRangerV2 \
  -s b1 \
  -G mm10 \
  -S FALSE \
  -d Droplet \
  -D TRUE \
  -F Seurat \
  -n 48 \
  -M TRUE \
  -E mouse-ensembl \ 
  -T MulticoreParam `

### The error for b1 sample:
`Completed DecontX. Total time: 47.5849 secs
Mon Aug  1 09:05:54 2022 ... Running 'SoupX'
Mon Aug  1 09:05:54 2022 ... Running 'SoupX' on sample: all_cells
Mon Aug  1 09:05:55 2022 ... Cluster info not given,
Mon Aug  1 09:05:55 2022 ...   generating with Scran SNN method.
2236 genes passed tf-idf cut-off and 309 soup quantile filter.  Taking the top 100.
Using 814 independent estimates of rho.
Estimated global rho of 0.70
Error in setContaminationFraction(sc, contEst, forceAccept = forceAccept) :
  Extremely high contamination estimated (0.7).  This likely represents a failure in estimating the contamination fraction.  Set forceAccept=TRUE to proceed with this value.
Calls: runCellQC ... .SoupXOneBatch -> <Anonymous> -> setContaminationFraction
Execution halted
`

### And the error for std* sample:
`Mon Aug  1 08:30:09 2022 ... Running 'perCellQCMetrics'
Mon Aug  1 08:30:12 2022 ... Running 'emptyDrops'
Error in .compute_ambient_stats(m, totals, lower = lower) :
  no counts available to estimate the ambient profile
Calls: runDropletQC ... <Anonymous> -> testEmptyDrops -> .compute_ambient_stats
Execution halted`

Thank you.

**Comment by rz2333** [comment]
Hi,

Thanks for using the sctk! Here is the fix to each of the error:

1. Error in the std* samples. I checked out the GEO repository. I guess for the std* samples, the authors shared the cells matrix (emptydrop already removed) and the raw matrix (including empty droplets) for b1 samples. If you check out the size of the matrix, you might find the b1 matrix has ~6M of barcodes. The emptyDrops only works on the raw matrix not the cells matrix and that's why the **'-d Droplet'** option doesn't work for the std* samples. For std* samples, you can set **'-d Cell'** which would skip the emptyDroplet detection step. 

2. Error in b1 sample. That's because the default parameters of the SoupX algorithm don't work for that specific dataset. We could use the yml file to tweak the parameters of the SoupX algorithm.  For example, we could try to lower the _tfidfmin_ parameters in the yml file and pass it to the sctk pipeline. 
[YAML_parameter.txt](https://github.com/compbiomed/singleCellTK/files/9235382/YAML_parameter.txt)

`docker run --rm -v ~/sc_Projects/Data/Cell_BM_Taxonomy:/SCTK_docker \ -it campbio/sctk_qc:2.6.0 \ -R SCTK_docker/b1 \ -P CellRangerV2 \ -s b1 \ -G mm10 \ -S FALSE \ -d Droplet \ -D TRUE \ -F Seurat \ -n 48 \ -M TRUE \ -E mouse-ensembl \ -T MulticoreParam \ -y SCTK_docker/YAML_parameter.txt`

Let's see whether that works. If not, it might need to further tweak other parameters in that function to make it work for a specific dataset. More parameters can be found here: https://camplab.net/sctk/v2.7.1/reference/runSoupX.html

Thanks,
Rui

**Comment by joshua-d-campbell** [comment]
Hi @XanderChen0530, just to add to what Rui said, you can also run the SCTK-QC functions directly in R. For example, you can try tweaking the parameters to SoupX using the `runSoupX` function. The `runCellQC` function is a wrapper can be used to run all the QC tools in the R console as well. You can also just skip SoupX if you can't get it to run and use DecontX for estimation of ambient RNA.

**Comment by XanderChen0530** [comment]
> Hi,
> 
> Thanks for using the sctk! Here is the fix to each of the error:
> 
> 1. Error in the std* samples. I checked out the GEO repository. I guess for the std* samples, the authors shared the cells matrix (emptydrop already removed) and the raw matrix (including empty droplets) for b1 samples. If you check out the size of the matrix, you might find the b1 matrix has ~6M of barcodes. The emptyDrops only works on the raw matrix not the cells matrix and that's why the **'-d Droplet'** option doesn't work for the std* samples. For std* samples, you can set **'-d Cell'** which would skip the emptyDroplet detection step.
> 2. Error in b1 sample. That's because the default parameters of the SoupX algorithm don't work for that specific dataset. We could use the yml file to tweak the parameters of the SoupX algorithm.  For example, we could try to lower the _tfidfmin_ parameters in the yml file and pass it to the sctk pipeline.
>    [YAML_parameter.txt](https://github.com/compbiomed/singleCellTK/files/9235382/YAML_parameter.txt)
> 
> `docker run --rm -v ~/sc_Projects/Data/Cell_BM_Taxonomy:/SCTK_docker \ -it campbio/sctk_qc:2.6.0 \ -R SCTK_docker/b1 \ -P CellRangerV2 \ -s b1 \ -G mm10 \ -S FALSE \ -d Droplet \ -D TRUE \ -F Seurat \ -n 48 \ -M TRUE \ -E mouse-ensembl \ -T MulticoreParam \ -y SCTK_docker/YAML_parameter.txt`
> 
> Let's see whether that works. If not, it might need to further tweak other parameters in that function to make it work for a specific dataset. More parameters can be found here: https://camplab.net/sctk/v2.7.1/reference/runSoupX.html
> 
> Thanks, Rui

Hi Rui,
Thank you for your help.
After our shared cloud server totally closed the right to use docker, I found using 'Rscript SCTK_runQC.R' works for me. However, for the b1 sample, I still can't pass parameters into sctk pipeline by setting -y even though I added 'forceAccept: TRUE'. It seems the method, 'Rscript SCTK_runQC.R', can't recognize these parameters. 
And when I use -R for the b2 sample, I am not sure whether the pipeline is running parallelly, cause there is a warning message, 'command not found: -n', at the end. But this did not happen when I use -b for the pbmc sample. 
Here is my yaml setting:
> ---
Params:   ### should not be omitted
  SoupX:
    tfidfMin: 0.6
    forceAccept: True
    
  SoupX_bg:
    tfidfMin: 0.6
    forceAccept: True
  
  ScDblFinder:
    BPPARAM: BiocParallel::MulticoreParam(workers = 24)
    
  DoubletFinder:
    nCores: 24

Thank you,
Xiaojun
